name: 'Deploy to Firebase Cloud Functions (only functions)'
author: 'dheshalj <dheshal.j@gmail.com>'
description: 'A GitHub Action to deploy to Firebase Cloud Functions'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'cloud'
  color: 'black'
